# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "pydantic>=2.13.4",
#     "typing>=3.10.0.0",
# ]
# ///
from typing import List, Optional, Union, Dict, Any

from pydantic import BaseModel, ConfigDict, Field


# --- Request Components ---

class ResponseFormat(BaseModel):
    model_config = ConfigDict(extra="allow")
    type: str = "text"  # Can be "text" or "json_object"


class ChatCompletionMessageParam(BaseModel):
    """Represents an item in the 'messages' array."""
    model_config = ConfigDict(extra="allow")
    role: str  # "system", "user", "assistant", "tool", or "function"
    content: Optional[Union[str, List[Dict[str, Any]]]] = None
    name: Optional[str] = None
    tool_call_id: Optional[str] = None


class FunctionDefinition(BaseModel):
    model_config = ConfigDict(extra="allow")
    name: str
    description: Optional[str] = None
    parameters: Dict[str, Any]  # JSON Schema object


class ToolDefinition(BaseModel):
    model_config = ConfigDict(extra="allow")
    type: str = "function"
    function: FunctionDefinition


class StreamOptions(BaseModel):
    model_config = ConfigDict(extra="allow")
    include_usage: Optional[bool] = None


# --- Main Request Schema ---

class OpenAIChatCompletionRequest(BaseModel):
    """Official OpenAI Chat Completion Request Schema with extra property tolerance."""
    model_config = ConfigDict(extra="allow")

    model: str
    messages: List[ChatCompletionMessageParam]

    # Common Parameters
    frequency_penalty: Optional[float] = Field(default=None, ge=-2.0, le=2.0)
    logit_bias: Optional[Dict[str, int]] = None
    logprobs: Optional[bool] = False
    top_logprobs: Optional[int] = Field(default=None, ge=0, le=20)
    max_tokens: Optional[int] = None
    max_completion_tokens: Optional[int] = None
    n: Optional[int] = Field(default=1, ge=1)
    presence_penalty: Optional[float] = Field(default=None, ge=-2.0, le=2.0)
    response_format: Optional[ResponseFormat] = None
    seed: Optional[int] = None
    stop: Optional[Union[str, List[str]]] = None
    stream: Optional[bool] = False
    stream_options: Optional[StreamOptions] = None
    temperature: Optional[float] = Field(default=None, ge=0.0, le=2.0)
    top_p: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    user: Optional[str] = None

    # Tools and Functions
    tools: Optional[List[ToolDefinition]] = None
    tool_choice: Optional[Union[str, Dict[str, Any]]] = None


# --- Response Components ---

class FunctionCall(BaseModel):
    model_config = ConfigDict(extra="allow")
    name: str
    arguments: str  # JSON string


class ToolCall(BaseModel):
    model_config = ConfigDict(extra="allow")
    id: str
    type: str = "function"
    function: FunctionCall


class ChatCompletionMessage(BaseModel):
    model_config = ConfigDict(extra="allow")
    role: Optional[str] = None
    content: Optional[str] = None
    refusal: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None
    reasoning_content: Optional[str] = Field(
        default=None,
        description="The reasoning content (chain of thought) generated by the model prior to the main response."
    )


class ChoiceLogprobs(BaseModel):
    model_config = ConfigDict(extra="allow")
    content: Optional[List[Dict[str, Any]]] = None


class ChatCompletionChoice(BaseModel):
    model_config = ConfigDict(extra="allow")
    index: int
    message: ChatCompletionMessage
    finish_reason: str = Field(
        description="Can be 'stop', 'length', 'tool_calls', 'content_filter', etc."
    )
    logprobs: Optional[ChoiceLogprobs] = None


class CompletionUsage(BaseModel):
    model_config = ConfigDict(extra="allow")
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    # Accounts for newer models containing reasoning or caching metrics
    prompt_tokens_details: Optional[Dict[str, int]] = None
    completion_tokens_details: Optional[Dict[str, int]] = None


class OpenAIResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str | None = None
    created: int = None
    model: str
    usage: Optional[CompletionUsage] = None
    system_fingerprint: Optional[str] = None


# --- Main Response Schema ---

class OpenAICompletionResponse(OpenAIResponse):
    """Official OpenAI Chat Completion Schema with undefined property tolerance."""
    object: str = "chat.completion"
    choices: List[ChatCompletionChoice]


# --- Streaming Components ---

class ChatCompletionChunkChoice(BaseModel):
    model_config = ConfigDict(extra="allow")
    index: int
    delta: ChatCompletionMessage
    finish_reason: Optional[str] = Field(
        default=None,
        description="Can be 'stop', 'length', 'tool_calls', or None during streaming."
    )
    logprobs: Optional[ChoiceLogprobs] = None


# --- Main Streaming Response Schema ---

class OpenAICompletionChunkResponse(OpenAIResponse):
    """Official OpenAI Chat Completion Chunk Schema (stream=True)."""
    object: str = "chat.completion.chunk"
    choices: List[ChatCompletionChunkChoice]
