llama-server ^
  -m "C:\Users\mfour\.lmstudio\models\lmstudio-community\gemma-4-E2B-it-GGUF\gemma-4-E2B-it-Q4_K_M.gguf" ^
  --ctx-size 65536 ^
  --batch-size 4096 ^
  --ubatch-size 2048 ^
  --jinja ^
  --cache-prompt ^
  --context-shift ^
  -ctk q8_0 ^
  -ctv q8_0 ^
  -fa on ^
  -ngl 99 ^
  -np 1 ^
  --kv-unified ^
  --port 8002