llama-server ^
  -m "C:\Users\mfour\.lmstudio\models\Tesslate\OmniCoder-9B-GGUF\omnicoder-9b-q4_k_m.gguf" ^
  --ctx-size 65536 ^
  --batch-size 4096 ^
  --ubatch-size 2048 ^
  --jinja ^
  --cache-prompt ^
  --context-shift ^
  -ctk q8_0 ^
  -ctv q8_0 ^
  -fa on ^
  -ngl 99 ^
  -np 1 ^
  --log-verbose ^
  --log-verbosity 5 ^
  --port 8002