input_stream: "HTTP_REQUEST_PAYLOAD:input"
output_stream: "HTTP_RESPONSE_PAYLOAD:output"
node: {
  name: "LLMExecutor"
  calculator: "HttpLLMCalculator"
  input_stream: "LOOPBACK:loopback"
  input_stream: "HTTP_REQUEST_PAYLOAD:input"
  input_side_packet: "LLM_NODE_RESOURCES:llm"
  output_stream: "LOOPBACK:loopback"
  output_stream: "HTTP_RESPONSE_PAYLOAD:output"
  input_stream_info: {
    tag_index: 'LOOPBACK:0',
    back_edge: true
  }
  node_options: {
    [type.googleapis.com / mediapipe.LLMCalculatorOptions]: {
      max_num_seqs: 1,
      device: "NPU",
      models_path: "./1",
      enable_prefix_caching: true,
      enable_tool_guided_generation: true,
      tool_parser: "qwen3coder",
      max_tokens_limit: 8192,
      plugin_config: '{"LOG_LEVEL": "LOG_INFO", "NPU_COMPILER_TYPE": "DRIVER", "PERFORMANCE_HINT": "LATENCY", "CACHE_DIR": "./models_cache/Qwen2.5-Coder-0.5B-Instruct-int4-sym-g128-r1", "MAX_PROMPT_LEN": 4096}'
    }
  }
  input_stream_handler {
    input_stream_handler: "SyncSetInputStreamHandler",
    options {
      [mediapipe.SyncSetInputStreamHandlerOptions.ext] {
        sync_set {
          tag_index: "LOOPBACK:0"
        }
      }
    }
  }
}
