input_stream: "HTTP_REQUEST_PAYLOAD:input"
output_stream: "HTTP_RESPONSE_PAYLOAD:output"
node: {
  name: "LLMExecutor"
  calculator: "HttpLLMCalculator"
  input_stream: "LOOPBACK:loopback"
  input_stream: "HTTP_REQUEST_PAYLOAD:input"
  input_side_packet: "LLM_NODE_RESOURCES:llm"
  output_stream: "LOOPBACK:loopback"
  output_stream: "HTTP_RESPONSE_PAYLOAD:output"
  input_stream_info: {
    tag_index: 'LOOPBACK:0',
    back_edge: true
  }
  node_options: {
    [type.googleapis.com / mediapipe.LLMCalculatorOptions]: {
      pipeline_type: 2, # LM_CB
      max_num_seqs: 1,
      device: "GPU",
      models_path: "./1",
      enable_prefix_caching: true,
      cache_size: 4,
      enable_tool_guided_generation: true,
      tool_parser: "hermes3",
      reasoning_parser: "qwen3",
      max_tokens_limit: 32768,
      plugin_config: '{"PERFORMANCE_HINT": "LATENCY", "CACHE_DIR": "./models_cache/Qwen3-8B-int4-sym-g128-r1"}'
      draft_models_path: "../Qwen3-1.7B-Instruct-int4-sym-g128-r1/1",
      draft_device: "GPU",
      draft_max_num_batched_tokens: 5
      draft_eagle3_mode: false,
      draft_dynamic_split_fuse: true
    }
  }
  input_stream_handler {
    input_stream_handler: "SyncSetInputStreamHandler",
    options {
      [mediapipe.SyncSetInputStreamHandlerOptions.ext] {
        sync_set {
          tag_index: "LOOPBACK:0"
        }
      }
    }
  }
}
